ratpackConfiguration:
  port: 5050
  isDevelopment: true
questionnDatabase:
  url: jdbc:h2:/tmp/questionn;mode=mysql
  username: questionn
  password: ""
databasesForQuery:
  default:
    url: jdbc:h2:/tmp/questionn;mode=mysql
    username: questionn
    password: ""
configurationPath: example/shopp
